source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'beauty-iOS-Swift' do
    
    pod 'Alamofire', '~> 4.4.0'
    pod 'Moya', '~> 8.0.2'
    
end
